"""add sync_tasks durable work queue

Revision ID: a1b2c3d4e5f6
Revises: c7f1a2b3d495
Create Date: 2026-05-21

Hand-written (not autogenerated) because the active-thread dedup index is a
PARTIAL unique index (postgresql_where) that Alembic autogenerate doesn't
reliably emit.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "c7f1a2b3d495"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "sync_tasks",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_email", sa.String(length=254), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "enqueued_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','in_progress','done','failed')",
            name="ck_sync_tasks_status",
        ),
    )
    # At most one ACTIVE row per thread — makes re-enqueue on every push a no-op.
    op.create_index(
        "uq_sync_tasks_active_thread",
        "sync_tasks",
        ["user_email", "gmail_thread_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending','in_progress')"),
    )
    # Worker claim query: filter by status, FIFO by next_attempt_at then id.
    op.create_index(
        "ix_sync_tasks_claim",
        "sync_tasks",
        ["status", "next_attempt_at", "id"],
    )


def downgrade() -> None:
    op.drop_index("ix_sync_tasks_claim", table_name="sync_tasks")
    op.drop_index("uq_sync_tasks_active_thread", table_name="sync_tasks")
    op.drop_table("sync_tasks")
